[package]
name = "rtc-share"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3"
serde = "1.0"
serde_json = "1.0"
tokio = "1.40"
tokio-tungstenite = "0.24"
#webrtc = "0.11"
webrtc = { path = "./webrtc-rs/webrtc" }
